INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE', 'en', 'page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE', 'it', 'pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_MODEL', 'en', 'page model');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_MODEL', 'it', 'modello pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_TITLE', 'en', 'page title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_TITLE', 'it', 'titolo pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NOT_ALLOWED', 'en', 'User not allowed');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NOT_ALLOWED', 'it', 'Utente non autorizzato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_NOT_FOUND', 'en', 'Page not found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PAGE_NOT_FOUND', 'it', 'Pagina non trovata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('GENERIC_ERROR', 'en', 'Generic Error');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('GENERIC_ERROR', 'it', 'Errore Generico');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC', 'it', 'Normale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC', 'en', 'Normal');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT', 'it', 'Avanzata');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT', 'en', 'Advanced');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO', 'it', 'Accedi con client normale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_BASIC_GOTO', 'en', 'Go to the administration with normal client');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO', 'it', 'Accedi con client avanzato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ADMINISTRATION_MINT_GOTO', 'en', 'Go to the administration with advanced client');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_FROM', 'en', 'From');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_FROM', 'it', 'Da');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_TO', 'en', 'To');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DATE_TO', 'it', 'A');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TEXT', 'en', 'Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TEXT', 'it', 'Testo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ALL', 'en', 'All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ALL', 'it', 'Tutte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_FROM', 'en', 'From');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_FROM', 'it', 'Da');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_TO', 'en', 'To');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NUMBER_TO', 'it', 'A');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_APPLY', 'en', 'Apply');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_APPLY', 'it', 'Applica');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_CONFIG_INTRO', 'en', 'Choose which content you want to add in this page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_CONFIG_INTRO', 'it', 'Scegli quali contenuti mostrare nella pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_CONFIGMYHOME', 'en', 'Page Content Configuration');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_CONFIGMYHOME', 'it', 'Configura la Pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_INSERTINTOCOLUMN', 'en', 'Inserting it into column');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_INSERTINTOCOLUMN', 'it', 'Inserendolo nella colonna');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_MOVE', 'en', 'Move');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_MOVE', 'it', 'Sposta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_RESET', 'en', 'Reset the Page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_RESET', 'it', 'Reimposta la pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_MOVETHISSHOWLET', 'en', 'Move this box');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_MOVETHISSHOWLET', 'it', 'Sposta questo box');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_RESET_INTRO', 'en', 'If you want to discard the current configuration you can reset the page.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_RESET_INTRO', 'it', 'Se desideri riportare la pagina alla configurazione predefinita, puoi resettare le impostazioni.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_SWAPITWITH', 'en', 'Swap it with');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_SWAPITWITH', 'it', 'Scambiandolo con');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_LOADING_INFO', 'it', 'Caricamento informazioni in corso...');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_LOADING_INFO', 'en', 'Loading...');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_ERROR_INFO', 'it', 'Si è verificato un errore, riprovare.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPMYPORTALPLUS_ERROR_INFO', 'en', 'An error has occurred, retry.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_CONFIRM_NEWPASS', 'it', 'Conferma nuova password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_CONFIRM_NEWPASS', 'en', 'Confirm new password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPASSWORD', 'it', 'Modifica Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPASSWORD', 'en', 'Edit Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPASSWORD_TITLE', 'it', 'Modifica Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPASSWORD_TITLE', 'en', 'Edit Password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPROFILE_TITLE', 'it', 'Modifica profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_EDITPROFILE_TITLE', 'en', 'Edit Profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEUP', 'it', 'Sposta su');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEUP', 'en', 'Move up');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEUP_IN', 'it', 'Sposta su in posizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEUP_IN', 'en', 'Move at position');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEDOWN', 'it', 'Sposta giu');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEDOWN', 'en', 'Move down');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEDOWN_IN', 'it', 'Sposta giu in posizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_MOVEDOWN_IN', 'en', 'Move down at position');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_REMOVE', 'it', 'Rimuovi dalla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ITEM_REMOVE', 'en', 'Remove from list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_MESSAGE_TITLE_FIELDERRORS', 'it', 'Attenzione, si sono verificati i seguenti errori nella compilazione del modulo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_MESSAGE_TITLE_FIELDERRORS', 'en', 'Warning, please check the module');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_NEWPASS', 'it', 'Nuova password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_NEWPASS', 'en', 'New password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_OLDPASSWORD', 'it', 'Vecchia password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_OLDPASSWORD', 'en', 'Old password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PASSWORD_UPDATED', 'it', 'La password è stata aggiornata correttamente.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PASSWORD_UPDATED', 'en', 'Your password updated successfully.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PROFILE_UPDATED', 'it', 'Profilo aggiornato correttamente.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PROFILE_UPDATED', 'en', 'Your profile is now updated.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_SAVE_PASSWORD', 'it', 'Salva password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_SAVE_PASSWORD', 'en', 'Save password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_SAVE_PROFILE', 'it', 'Salva il profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_SAVE_PROFILE', 'en', 'Save profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ADDITEM_LIST', 'it', 'Aggiungi nuovo elemento alla lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ADDITEM_LIST', 'en', 'Add an element to the list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PUBLICCHECK', 'it', 'Il mio profilo è pubblico');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PUBLICCHECK', 'en', 'My profile is public');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_YES', 'it', 'Si');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_YES', 'en', 'Yes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_NO', 'it', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_NO', 'en', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_BOTH_YES_AND_NO', 'it', 'Indifferente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_BOTH_YES_AND_NO', 'en', 'Both');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT', 'it', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MANDATORY_SHORT', 'en', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MANDATORY_FULL', 'en', 'Mandatory');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT', 'it', 'Min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MINLENGTH_SHORT', 'en', 'Min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL', 'it', 'Lunghezza Minima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MINLENGTH_FULL', 'en', 'Minimum length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT', 'it', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MAXLENGTH_SHORT', 'en', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL', 'it', 'Lunghezza Massima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ENTITY_ATTRIBUTE_MAXLENGTH_FULL', 'en', 'Maximum length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_CURRENT_USER_WITHOUT_PROFILE', 'it', 'Utente corrente senza profilo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_CURRENT_USER_WITHOUT_PROFILE', 'en', 'Current user without profile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_4', 'it', 'Walter');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_4', 'en', 'Walter');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_4', 'it', 'customer user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_4', 'en', 'customer user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_4', 'it', 'walter');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_4', 'en', 'walter');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_4', 'it', 'pass');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_4', 'en', 'pass');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LABEL_USER', 'it', 'utente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LABEL_USER', 'en', 'user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LABEL_PASS', 'it', 'password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LABEL_PASS', 'en', 'password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_GUEST', 'it', 'Ospite');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_GUEST', 'en', 'Guest');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_GUEST', 'it', 'user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_GUEST', 'en', 'user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_GUEST', 'it', 'guest');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_GUEST', 'en', 'guest');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_GUEST', 'it', 'pass');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_GUEST', 'en', 'pass');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_1', 'it', 'admin');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_1', 'en', 'admin');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_2', 'it', 'intranet user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_2', 'en', 'intranet user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_3', 'it', 'customer user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_DESCR_3', 'en', 'customer user');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LANG_en', 'it', 'English');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LANG_en', 'en', 'English');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LANG_it', 'it', 'Italiano');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LANG_it', 'en', 'Italiano');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_STATUS_CREDENTIALS_INVALID', 'it', 'Credenziali non valide.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_STATUS_CREDENTIALS_INVALID', 'en', 'Username/Password not valid.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USERNAME', 'it', 'Utente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USERNAME', 'en', 'Username');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('COPYRIGHT', 'it', 'Copyright &copy; Entando S.r.l. 2013');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('COPYRIGHT', 'en', 'Copyright &copy; Entando S.r.l. 2013');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCHED_FOR', 'en', 'You searched for');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCHED_FOR', 'it', 'Hai cercato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_FORM_TITLE', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_FORM_TITLE', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_GO', 'en', 'Go');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_GO', 'it', 'Vai');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_NOTHING_FOUND', 'en', 'Nothing found.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_NOTHING_FOUND', 'it', 'Nessun risultato trovato.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS', 'en', 'Search results');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS', 'it', 'Risultati della ricerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_INTRO', 'en', 'You''ve found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_INTRO', 'it', 'Sono stati trovati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_OUTRO', 'en', 'results');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_RESULTS_OUTRO', 'it', 'risultati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME', 'it', 'Benvenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME', 'en', 'Welcome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LINKS', 'en', 'Links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LINKS', 'it', 'Approfondimenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ATTACHMENTS', 'en', 'Attachments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ATTACHMENTS', 'it', 'Allegati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE1_TITLE', 'en', 'Choose new style');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE1_TITLE', 'it', 'Scegli questo stile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE2_TITLE', 'en', 'Choose new style');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE2_TITLE', 'it', 'Scegli questo stile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE3_TITLE', 'en', 'Choose new style');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ARCHIVE_STYLE3_TITLE', 'it', 'Scegli questo stile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRNome', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRNome', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRCognome', 'it', 'Cognome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRCognome', 'en', 'Surname');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRemail', 'it', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRemail', 'en', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_1', 'en', 'Jeff');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_1', 'it', 'Jeff');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_1', 'en', 'jeff');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_1', 'it', 'jeff');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_1', 'en', 'adminadmin');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_1', 'it', 'adminadmin');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_2', 'en', 'Caroline');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_2', 'it', 'Caroline');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_2', 'en', 'caroline');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_2', 'it', 'caroline');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_3', 'en', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_NAME_3', 'it', 'Max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_3', 'en', 'max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_LOGIN_3', 'it', 'max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_3', 'en', 'customer');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_3', 'it', 'customer');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_2', 'en', 'intranet');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('USER_PASS_2', 'it', 'intranet');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsharewith_TITLE', 'it', 'Condividi con...');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsharewith_TITLE', 'en', 'Share with...');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsharewith_NOSCRIPT', 'en', 'This feature needs a Javascript enabled browser.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsharewith_NOSCRIPT', 'it', 'Questa funzionalità ha bisogno di un browser con Javascript attivato.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD', 'en', 'The value for field');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_FIELD', 'it', 'Il valore del campo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT', 'en', 'is invalid');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jacms_LIST_VIEWER_INVALID_FORMAT', 'it', 'non è corretto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PORTAL_TITLE', 'it', 'Entando Demo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PORTAL_TITLE', 'en', 'Entando Demo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PREV', 'it', 'Prec');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('PREV', 'en', 'Prev');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NEXT', 'it', 'Succ');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NEXT', 'en', 'Next');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DOWNLOAD', 'it', 'Download');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('DOWNLOAD', 'en', 'Download');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRazienda', 'en', 'Company');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_ATTRazienda', 'it', 'Azienda');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LIST_VIEWER_EMPTY', 'it', 'Nessun risultato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LIST_VIEWER_EMPTY', 'en', 'Nothing found');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGIN', 'it', 'Login');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGIN', 'en', 'Sign In');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGOUT', 'it', 'Logout');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGOUT', 'en', 'Sign Out');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_THIS_CONTENT', 'en', 'Edit this content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_THIS_CONTENT', 'it', 'Modifica questo contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TWEET', 'en', 'Tweet');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('TWEET', 'it', 'Tweet');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('BEGIN_GUEST', 'en', 'Begin guest');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('BEGIN_GUEST', 'it', 'Begin guest');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_caroline', 'en', '<strong>Welcome Caroline!</strong> you are a co-worker and you can access to the intranet area!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_caroline', 'it', '<strong>Benvenuta Caroline!</strong> sei una collaboratrice e puoi accedere alla sezione intranet!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_max', 'en', '<strong>Welcome Max!</strong> you are a customer and you can access to the customer area!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_max', 'it', '<strong>Welcome Max!</strong> sei un cliente e puoi accedere alla sezione clienti!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_jeff', 'en', '<strong>Welcome, Jeff</strong>! you are an administrator with full control over the entire portal!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_jeff', 'it', '<strong>Benvenuto, Jeff!</strong> sei un amministratore con controllo completo di tutto il portale!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_admin', 'en', '<strong>Welcome Admin!</strong> you are an administrator with full control over the entire portal!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_admin', 'it', '<strong>Benvenuto Admin!</strong> sei un amministratore con controllo completo di tutto il portale!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGIN_AS', 'en', 'Sign in as');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('LOGIN_AS', 'it', 'Accedi come');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN', 'en', 'Please Sign In');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN', 'it', 'E'' necessario effettuare l''accesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN_AGAIN', 'en', 'Please Sign Out and Sign In again.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN_AGAIN', 'it', 'E'' necessario riloggarsi.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD', 'en', 'Please Sign Out and Sign In again in order to change your password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpuserprofile_PLEASE_LOGIN_TO_EDIT_PASSWORD', 'it', 'E'' necessario effettuare l''accesso per cambiare la password');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_BY', 'en', 'Search by');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SEARCH_BY', 'it', 'Cerca per');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_USER_NOT_ALLOWED', 'it', 'Operazione non consentita');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_USER_NOT_ALLOWED', 'en', 'Operation not allowed');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_GENERIC_ERROR', 'it', 'Si è verificato un errore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_GENERIC_ERROR', 'en', 'An error is happened');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_ERRORS', 'it', 'Errori');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_ERRORS', 'en', 'Errors');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_WORKING_ON', 'it', 'Stai lavorando a');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_WORKING_ON', 'en', 'You are working on');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONTENT_FREE', 'it', 'Contenuto visibile a tutti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONTENT_FREE', 'en', 'Content visible to all');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SAVE', 'it', 'Salva');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SAVE', 'en', 'Save');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH', 'it', 'Cerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH', 'en', 'Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONTINUE', 'it', 'Continua');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONTINUE', 'en', 'Continue');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_URL', 'it', 'Link a url');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_URL', 'en', 'Link to url');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_PAGE', 'it', 'Link a pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_PAGE', 'en', 'Link to page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_CONTENT', 'it', 'Link a contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_CONTENT', 'en', 'Link to content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_CONTENT_ON_PAGE', 'it', 'su pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINK_TO_CONTENT_ON_PAGE', 'en', 'on page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE', 'it', 'Configura');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE', 'en', 'Configure');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REMOVE', 'it', 'Rimuovi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REMOVE', 'en', 'Remove');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_DO_THIS_ON_DEFAULT_LANG', 'it', 'Questo Attributo può essere usato solamente nella sezione della lingua di default');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_DO_THIS_ON_DEFAULT_LANG', 'en', 'You can only fill this Attribute from the default language section');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_ATTRIBUTE', 'it', 'Configura Attributo Link');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_ATTRIBUTE', 'en', 'Configure Link Attribute');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STEP_1_OF_2', 'it', '(Passo 1 di 2)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STEP_1_OF_2', 'en', '(Step 1 of 2)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STEP_2_OF_2', 'it', '(Passo 2 di 2)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STEP_2_OF_2', 'en', '(Step 2 of 2)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_LINK_TYPE', 'it', 'Scelta tipo di link');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_LINK_TYPE', 'en', 'Choose link type');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_TO_CONTENT', 'it', 'Scegli un Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_TO_CONTENT', 'en', 'Choose a Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH_FOR_DESCR', 'it', 'Cerca per Descrizione:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH_FOR_DESCR', 'en', 'Search for Description:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH_FILTERS', 'it', 'Raffina la Ricerca');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SEARCH_FILTERS', 'en', 'Refine your Search');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_TYPE', 'it', 'Tipo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_TYPE', 'en', 'Type');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SELECT_ALL', 'it', 'Tutti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_SELECT_ALL', 'en', 'All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STATUS', 'it', 'Stato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_STATUS', 'en', 'Status');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINKATTRIBUTE_CONTENT_SUMMARY', 'it', 'La tabella mostra l''elenco dei contenuti disponibili per la configurazione del LinkAttribute. Per ogni contenuto è indicata la descrizione, il codice, il Gruppo di Utenti a cui appartiene, la data di creazione e quella di ultima modifica.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINKATTRIBUTE_CONTENT_SUMMARY', 'en', 'This table shows a list of contents available for the configuration of LinkAttribute. For each content it shows description, code, group, date of creation and of last modification.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINKATTRIBUTE_CONTENT_CAPTION', 'it', 'Lista Contenuti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LINKATTRIBUTE_CONTENT_CAPTION', 'en', 'Content List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_GROUP', 'it', 'Gruppo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_GROUP', 'en', 'Group');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CREATION_DATE', 'it', 'Creazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CREATION_DATE', 'en', 'Creation');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LAST_EDIT', 'it', 'Ultima Modifica');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LAST_EDIT', 'en', 'Last Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_MAKE_CONTENT_ON_PAGE', 'it', 'Prosegui scegliendo anche una Pagina di pubblicazione temporanea');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_eMail', 'en', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_MAKE_CONTENT_ON_PAGE', 'en', 'Continue choosing a Page for on-the-fly publishing');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_TO_PAGE', 'it', 'Scegli una  Pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_LINK_TO_PAGE', 'en', 'Choose a Page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FOR_THE_CONTENT', 'it', 'per il Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FOR_THE_CONTENT', 'en', 'for the Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_PAGE_TREE', 'it', 'Albero delle Pagine');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_PAGE_TREE', 'en', 'Page Tree');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIRM', 'it', 'Conferma');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIRM', 'en', 'Confirm');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_URL', 'it', 'Inserisci un URL valido (esempio: http://www.miosito.it/)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CONFIGURE_URL', 'en', 'Insert a valid URL (ex: http://www.miosito.it/)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_URL', 'it', 'URL');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_URL', 'en', 'URL');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_PREVIOUS_LINK', 'it', 'In precedenza era stato configurato un');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_PREVIOUS_LINK', 'en', 'Previously configured as');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_EDIT_CONTENT', 'it', 'Modifica');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_EDIT_CONTENT', 'en', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REMOVE_CONTENT', 'it', 'Elimina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REMOVE_CONTENT', 'en', 'Remove');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_CONTENT', 'it', 'Crea un nuovo contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_CONTENT', 'en', 'Create a new content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_ATTACH', 'it', 'Scegli un allegato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_ATTACH', 'en', 'Choose an attachment');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_IMAGE', 'it', 'Scegli un''immagine');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CHOOSE_IMAGE', 'en', 'Choose an image');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CATEGORY', 'it', 'Categoria');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CATEGORY', 'en', 'Category');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_JOIN', 'it', 'Associa');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_JOIN', 'en', 'Join');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_JOIN_TO', 'it', 'Associa al Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_JOIN_TO', 'en', 'Join to Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_RESOURCE', 'en', 'New Resource');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_RESOURCE', 'it', 'Nuova Risorsa');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_BACK_TO_CONTENT', 'en', 'Back to the Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_BACK_TO_CONTENT', 'it', 'Torna al Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REQUIRED_SHORT', 'en', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REQUIRED_SHORT', 'it', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REQUIRED_FULL', 'en', 'Required');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_REQUIRED_FULL', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INFO', 'en', 'Info');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INFO', 'it', 'Info');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FILE', 'en', 'File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FILE', 'it', 'File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CATEGORIES_MANAGEMENT', 'en', 'Categories Management');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CATEGORIES_MANAGEMENT', 'it', 'Gestione delle Categorie');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORIES_SUMMARY', 'en', 'The table shows the categories associated with the resource. For each category shows the description (also known as the title), and you can remove it from the table.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORIES_SUMMARY', 'it', 'La tabella mostra le Categorie associate alla Risorsa. Per ogni categoria è indicata la descrizione (nota anche come titolo), ed è possibile rimuoverla dalla tabella.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORIES', 'en', 'Categories');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORIES', 'it', 'Categorie');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORY', 'en', 'Category');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_RESOURCES_CATEGORY', 'it', 'Categoria');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_INFO', 'en', 'The fields marked with * are required.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_INFO', 'it', 'I campi contrassegnati dal simbolo * sono obbligatori.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_FULL', 'en', 'Mandatory');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_FULL', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_SHORT', 'en', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MANDATORY_SHORT', 'it', '*');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_FULL', 'en', 'Max Length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_FULL', 'it', 'Lunghezza massima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_SHORT', 'en', 'max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MAXLENGTH_SHORT', 'it', 'max');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_FULL', 'en', 'Min Length');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_FULL', 'it', 'Lunghezza minima');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_SHORT', 'en', 'min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ENTITY_ATTR_FLAG_MINLENGTH_SHORT', 'it', 'min');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_INVIA', 'en', 'Send');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_INVIA', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGE_SAVE_CONFIRMATION', 'it', 'Il messaggio è stato inviato correttamente. Se vuoi inviaci un''altra');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGE_SAVE_CONFIRMATION', 'en', 'The message has been sent successfully. If you need, send us another');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGE_REQUEST_LINK', 'en', 'request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGE_REQUEST_LINK', 'it', 'richiesta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_SELECT', 'en', 'Select');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_SELECT', 'it', 'Seleziona');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGETYPE', 'it', 'Scegliere un tipo di messaggio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_MESSAGETYPE', 'en', 'Choose a message type');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CHOOSE_TYPE', 'it', 'Scegli e continua');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CHOOSE_TYPE', 'en', 'Select and continue');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ERRORS', 'it', 'Errori durante la compilazione del modulo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ERRORS', 'en', 'Errors occured');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_YES', 'it', 'Si');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_YES', 'en', 'Yes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_NO', 'it', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_NO', 'en', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_BOTH_YES_AND_NO', 'it', 'Indifferente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_BOTH_YES_AND_NO', 'en', 'Both');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ERRORS_HAPPENED', 'it', 'Si sono verificati degli errori!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_ERRORS_HAPPENED', 'en', 'An error has happened!');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Company', 'it', 'Azienda');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Company', 'en', 'Company');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Address', 'it', 'Indirizzo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Address', 'en', 'Address');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_eMail', 'it', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Note', 'it', 'Messaggio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_Note', 'en', 'Message');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_SAVE', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_COM_SAVE', 'en', 'Send');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_CONTENT_RATING', 'it', 'Valutazione del Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_CONTENT_RATING', 'en', 'Content Rating');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_AVG_RATING', 'it', 'Voto medio dei lettori:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_AVG_RATING', 'en', 'Average users rating:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTERS_NUM', 'it', 'votanti.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTERS_NUM', 'en', 'voters.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTERS_NULL', 'it', 'Ancora nessun utente ha votato questo contenuto.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTERS_NULL', 'en', 'No rating yet.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTE', 'it', 'Valuta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTE', 'en', 'Rate it Now');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTE_SUBMIT', 'it', 'Invia la Valutazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_VOTE_SUBMIT', 'en', 'Send Rating');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENTS', 'it', 'Commenti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENTS', 'en', 'Comments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_AUTHOR', 'it', 'Autore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_AUTHOR', 'en', 'Author');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_DATE', 'it', 'Data');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_DATE', 'en', 'Date');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_TEXT', 'it', 'Testo Commento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_TEXT', 'en', 'Comment Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_DELETE', 'it', 'Cancella');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_DELETE', 'en', 'Delete');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_RATING', 'it', 'Valutazione Commento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_RATING', 'en', 'Comment Rating');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_NORATING', 'it', 'Nessuna valutazione da parte degli utenti.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_NORATING', 'en', 'No rating yet.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_LABEL_RATING', 'it', 'Voto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_LABEL_RATING', 'en', 'Rating Value');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_SEND', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_SEND', 'en', 'Send');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_THE_CONTENT', 'it', 'Commenta il Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENT_THE_CONTENT', 'en', 'Comment this Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_LABEL_COMMENTTEXT', 'it', 'Testo del Commento');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_LABEL_COMMENTTEXT', 'en', 'Comment Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENTS_NULL', 'it', 'Ancora nessun commento per questo contenuto.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpcontentfeedback_COMMENTS_NULL', 'en', 'No comments yet.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ACTIVE_QUESTIONNAIRE', 'en', 'active Questionnaires');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ACTIVE_QUESTIONNAIRE', 'it', 'questionari attivi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_AGE', 'en', 'Age');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_AGE', 'it', 'Età');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ANSWER_NUMBER', 'en', 'response number');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ANSWER_NUMBER', 'it', 'risposta numero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ANSWERS', 'en', 'Answers');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ANSWERS', 'it', 'Risposte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ARCHIVE_ENDDAY', 'en', 'and expired');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ARCHIVE_ENDDAY', 'it', 'ed è scaduto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_BEGIN', 'en', 'Begins');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_BEGIN', 'it', 'Inizia il');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_COUNTRY', 'en', 'City');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_COUNTRY', 'it', 'Città');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ENDDAY', 'en', 'and expires');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ENDDAY', 'it', 'e scadrà');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_ALREADY_VOTED', 'en', 'Mistake! You have already voted.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_ALREADY_VOTED', 'it', 'Errore! Hai già votato.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_EXPIRED_SURVEY', 'en', 'Mistake! The survey is already expired.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_EXPIRED_SURVEY', 'it', 'Errore! Il sondaggio è scaduto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_FINALRESULTNOTALLOWED', 'en', 'Mistake! The display of final results is not allowed.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_FINALRESULTNOTALLOWED', 'it', 'Errore! La visualizzazione dei risultati finali non è permessa.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_NOTBEGUNYET', 'en', 'Mistake! You have not yet begun.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_NOTBEGUNYET', 'it', 'Errore! Non hai ancora cominciato.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_NULL_VOTER_RESPONSE', 'en', 'Mistake! The number of responses is zero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_NULL_VOTER_RESPONSE', 'it', 'Errore! Il numero di risposte è nullo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_PARTIALRESULTSNOTALLOWED', 'en', 'Mistake! Display of partial results is not allowed.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_PARTIALRESULTSNOTALLOWED', 'it', 'Errore! La visualizzazione dei risultati parziali non è permessa.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_USER_NOT_ALLOWED', 'en', 'Mistake! Unauthorized.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_ERROR_USER_NOT_ALLOWED', 'it', 'Errore! Utente non autorizzato.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_FINAL_RESULTS', 'en', 'Final Results');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_FINAL_RESULTS', 'it', 'Risultati finali');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_FREE_TEXT', 'en', 'Free Text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_FREE_TEXT', 'it', 'Testo Libero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO', 'en', 'Send');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_ACTIVE_POLLS', 'en', 'active Polls');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_ACTIVE_POLLS', 'it', 'sondaggi attivi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_ACTIVE_POLLS', 'en', 'Go to the list of active polls');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_ACTIVE_POLLS', 'it', 'Vai alla lista dei sondaggi attivi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_ACTIVE_QUESTIONNAIRE', 'en', 'Go to the list of active surveys');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_ACTIVE_QUESTIONNAIRE', 'it', 'Vai alla lista dei questionari attivi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_POLL', 'en', 'Go to');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_POLL', 'it', 'Vai a');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_POLL_ARCHIVE', 'en', 'Go to surveys');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_POLL_ARCHIVE', 'it', 'Vai all''archivio sondaggi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_QUESTIONNAIRE', 'en', 'Vai a');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_QUESTIONNAIRE', 'it', 'Vai a');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_QUESTIONNAIRE_ARCHIVE', 'en', 'Go to questionnaires');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_GO_TO_QUESTIONNAIRE_ARCHIVE', 'it', 'Vai all''archivio questionari');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_INSERT_FREE_TEXT', 'en', 'Enter free text');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_INSERT_FREE_TEXT', 'it', 'Inserisci il testo libero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_MAX_ANSWERS', 'en', 'Maximum number of responses');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_MAX_ANSWERS', 'it', 'Numero massimo di risposte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_MIN_ANSWERS', 'en', 'Minimum number of responses');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_MIN_ANSWERS', 'it', 'Numero minimo di risposte');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_OBTAINED', 'en', 'scored');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_OBTAINED', 'it', 'ha ottenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PARTIAL_RESULTS', 'en', 'Subtotals');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PARTIAL_RESULTS', 'it', 'Risultati parziali');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PERSON', 'en', 'people.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PERSON', 'it', 'persone.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL', 'en', 'poll');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL', 'it', 'sondaggio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL_ARCHIVE', 'en', 'Archive');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL_ARCHIVE', 'it', 'Archivio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL_STARTDAY', 'en', 'The survey was published');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLL_STARTDAY', 'it', 'Il sondaggio è stato pubblicato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS', 'en', 'Polls');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS', 'it', 'Sondaggi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_ARCHIVE_INTRO', 'en', 'If you want you can go back to');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_ARCHIVE_INTRO', 'it', 'Se vuoi puoi tornare ai');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_LIST', 'en', 'List active polls');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_LIST', 'it', 'Lista dei sondaggi attivi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_LIST_INTRO', 'en', 'If you want you can see the results of polls ended in');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_POLLS_LIST_INTRO', 'it', 'Se vuoi puoi vedere i risultati dei sondaggi scaduti nell''');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PROFILE_NEEDED', 'en', 'It takes some of your data. Thank you for your cooperation.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_PROFILE_NEEDED', 'it', 'Sono necessari alcuni tuoi dati anagrafici. Grazie per la collaborazione.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTION', 'en', 'Question');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTION', 'it', 'Domanda');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTION_OF', 'en', 'of');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTION_OF', 'it', 'di');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTIONNAIRE_ARCHIVE', 'en', 'Archive');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTIONNAIRE_ARCHIVE', 'it', 'Archivio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTIONNAIRE_LIST_INTRO', 'en', 'If you want, you can see the list of expired surveys browsing the');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_QUESTIONNAIRE_LIST_INTRO', 'it', 'Se vuoi puoi vedere i questionari scaduti nell''');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SEX', 'en', 'Gender');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SEX', 'it', 'Sesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SURVEY', 'en', 'questionnaire');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SURVEY', 'it', 'questionario');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SURVEY_STARTDAY', 'en', 'The questionnaire was posted');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_SURVEY_STARTDAY', 'it', 'Il questionario è stato pubblicato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_THANKS_FOR', 'en', 'Thank you for cooperating. If you want you can return to the list');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_THANKS_FOR', 'it', 'Grazie per aver collaborato. Se vuoi puoi tornare alla lista dei');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_TITLE', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_TITLE', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_VOTED_TOT', 'en', 'All voted');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_VOTED_TOT', 'it', 'Hanno votato in tutto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_VOTES', 'en', 'votes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_VOTES', 'it', 'voti');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_HAVE_NOT_VOTED', 'en', 'You have not voted');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_HAVE_NOT_VOTED', 'it', 'Non hai ancora votato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_HAVE_VOTED', 'en', 'You have already voted');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_HAVE_VOTED', 'it', 'Hai già votato');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_NOT_VOTED', 'en', '(You have not voted)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_NOT_VOTED', 'it', '(Non hai ancora votato)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_VOTED', 'en', '(You have already voted)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('JPSURVEY_YOU_VOTED', 'it', '(Hai già votato)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsurvey_POLLS_ARCHIVE_LIST_TITLE', 'it', 'Archivio dei Sondaggi');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpsurvey_POLLS_ARCHIVE_LIST_TITLE', 'en', 'Polls Archive');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CONTENT_CHANGED', 'it', 'Il contenuto è stato salvato correttamente. La pagina si sta ricaricando.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('CONTENT_CHANGED', 'en', 'Content saved. This page will be reloaded');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_CONTENT', 'it', 'Modifica Contenuto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_CONTENT', 'en', 'Edit Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WIDGET_EDIT_POPUP_TITLE', 'it', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WIDGET_EDIT_POPUP_TITLE', 'en', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FASTCONTENTEDIT_SHOWLET_TITLE', 'it', 'Modifica Contenuto da Frontend');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_FASTCONTENTEDIT_SHOWLET_TITLE', 'en', 'Edit Content');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INTRO_en', 'it', 'Inglese');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INTRO_en', 'en', 'English');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INTRO_it', 'it', 'Italiano');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_INTRO_it', 'en', 'Italian');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Date', 'it', 'Data');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Date', 'en', 'Date');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Body', 'it', 'Testo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Body', 'en', 'Body');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Image1', 'it', 'Immagine 1');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Image1', 'en', 'Image 1');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Image2', 'it', 'Immagine 2');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Image2', 'en', 'Image 2');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Attach', 'it', 'Allegati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Attach', 'en', 'Attachments');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Links', 'it', 'Link correlati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Links', 'en', 'Related links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LIST', 'it', 'Lista');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LIST', 'en', 'List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_COM', 'it', 'Form Azienda');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_COM', 'en', 'Company Form');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_ATTACH', 'en', 'New File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_ATTACH', 'it', 'Nuovo File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_IMAGE', 'it', 'Nuovo File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_LABEL_NEW_IMAGE', 'en', 'New File');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('VIEW_ALL', 'it', 'View All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('VIEW_ALL', 'en', 'View All');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_CONTENT_BACKOFFICE', 'en', 'Edit Content (Backoffice)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('EDIT_CONTENT_BACKOFFICE', 'it', 'Modifica Contenuto (Backoffice)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CNG_Title', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CNG_Title', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CNG_Abstract', 'en', 'Abstract');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_CNG_Abstract', 'it', 'Estratto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Title', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Title', 'it', 'Titolo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Abstract', 'en', 'Abstract');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfastcontentedit_NEW_Abstract', 'it', 'Estratto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('MESSAGE_TITLE_FIELDERRORS', 'en', 'Error');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('MESSAGE_TITLE_FIELDERRORS', 'it', 'Errore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Name', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Name', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Surname', 'en', 'Surname');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Surname', 'it', 'Cognome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Address', 'en', 'Address');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Address', 'it', 'Indirizzo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_eMail', 'en', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_eMail', 'it', 'Email');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Date', 'en', 'Birthday');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Date', 'it', 'Data di nascita');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Number', 'en', 'Height (cm)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Number', 'it', 'Altezza (cm)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Text', 'en', 'Personal WebSite');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Text', 'it', 'Sito Personale');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Longtext', 'en', 'Note');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Longtext', 'it', 'Note');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_SAVE', 'en', 'Send');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_SAVE', 'it', 'Invia');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Enumerator', 'en', 'Contract Type');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_PER_Enumerator', 'it', 'Tipo Contratto');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_PER', 'en', 'User Form');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_PER', 'it', 'Form Utente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SLOGAN_TITLE', 'en', 'Welcome to Entando Portal Demo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SLOGAN_TITLE', 'it', 'Benvenuto nel Portale Demo di Entando');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCES', 'it', 'Risorse API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCES', 'en', 'API Resources');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_ERROR', 'it', 'Errore');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_ERROR', 'en', 'Errors');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE', 'it', 'Risorsa');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE', 'en', 'Resource');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS', 'it', 'Vai al dettaglio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_DETAILS', 'en', 'Go to details');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF', 'it', 'Non Attivo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_OFF', 'en', 'Not Active');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE', 'it', 'Attivo, Accesso Libero');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_FREE', 'en', 'Active, Free Access');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH', 'it', 'Attivo, Utenti Registrati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_AUTH', 'en', 'Active, Registered Users');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK', 'it', 'Metodo Attivo, Utenti Registrati con Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_LOCK', 'en', 'Active, Registered Users with Permission');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA', 'it', 'Metodo Non Disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_STATUS_NA', 'en', 'Method Not Available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES', 'it', 'Non ci sono Risorse API disponibili.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_NO_RESOURCES', 'en', 'No API Resources available at the moment.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY', 'it', 'La tabella elenaca le Risorse API disponibile nel sistema. Nome della risorsa, la sua descrizione e lo stato di ciascun metodo.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_TABLE_SUMMARY', 'en', 'The table lists the API Resources available in the system. Method name, description, group and the status of each method.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE', 'it', 'Namespace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_NAMESPACE', 'en', 'Namespace');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE', 'it', 'Sorgente');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_SOURCE', 'en', 'Source');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI', 'it', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_RESOURCE_URI', 'en', 'URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION', 'it', 'Estensione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION', 'en', 'Extension');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE', 'it', '''.xml'' per la risposta in formato xml e ''.json'' per la risposta in formato json.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_EXTENSION_NOTE', 'en', '''.xml'' for response in xml format and ''.json'' for json.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_KO', 'it', 'Non disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_KO', 'en', 'Not available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD', 'it', 'Metodo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD', 'en', 'Method');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_OK', 'it', 'Disponibile');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_OK', 'en', 'Available');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION', 'it', 'Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTHORIZATION', 'en', 'Authorization');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE', 'it', 'Nessuna, questo metodo è pubblico');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_FREE', 'en', 'None, this method is public');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM', 'it', 'Utenti registrati con permesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_WITH_PERM', 'en', 'Registered users with permission');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE', 'it', 'Utenti registrati');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_AUTH_SIMPLE', 'en', 'Registered users');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS', 'it', 'Schema XML');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMAS', 'en', 'XML Schemas');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ', 'it', 'Richiesta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_REQ', 'en', 'Request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP', 'it', 'Risposta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_SCHEMA_RESP', 'en', 'Response');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM', 'it', 'Questa tabella mostra i parametri per la richiesta del metodo. Per ciascuno di essi ci sono tre colonne: il nome del parametro, la descrizione del parametro e l''indicazione di obbligatorietà.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_PARAMS_SUMM', 'en', 'This table shows the request parameters for this method. For each of them there are three columns: the parameter name, the parameter description and whether if it''s mandatory or not.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS', 'it', 'Parametri');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_METHOD_REQUEST_PARAMS', 'en', 'Parameters');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_PARAM_REQUIRED', 'en', 'Mandatory');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('YES', 'it', 'Si');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('YES', 'en', 'Yes');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NO', 'it', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('NO', 'en', 'No');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_LIST', 'it', 'Lista delle Risorse API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_LIST', 'en', 'API Resource List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST', 'it', 'Lista Servizi API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_GOTO_SERVICE_LIST', 'en', 'API Service List');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICES', 'it', 'Servizi API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICES', 'en', 'API Services');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE', 'it', 'Servizio API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE', 'en', 'API Service');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API', 'it', 'Risorsa API');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARENT_API', 'en', 'Parent API Resource');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY', 'it', 'Chiave');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_KEY', 'en', 'Key');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION', 'it', 'Autorizzazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTHORIZATION', 'en', 'Authority');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE', 'it', 'Libera');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_FREE', 'en', 'Free');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_SIMPLE', 'it', 'Autenticazione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_SIMPLE', 'en', 'Simple Autentication');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_WITH_PERM', 'it', 'Autenticazione con permesso');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_WITH_PERM', 'en', 'Authentication with permission');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_WITH_GROUP', 'it', 'Autenticazione con gruppo');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_AUTH_WITH_GROUP', 'en', 'Authentication with group');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_URI', 'it', 'Service URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_URI', 'en', 'Service URI');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMAS', 'it', 'XML Schema');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMAS', 'en', 'XML Schema');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMA_RESP', 'it', 'Risposta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_SCHEMA_RESP', 'en', 'Response');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS_SUMMARY', 'it', 'Summary..');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS_SUMMARY', 'en', 'Summary..');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS', 'it', 'Parametri');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAMETERS', 'en', 'Parameters');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_NAME', 'it', 'Nome');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_NAME', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_REQUIRED', 'it', 'Obbligatorio');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_REQUIRED', 'en', 'Required');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DEFAULT_VALUE', 'it', 'Default');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_PARAM_DEFAULT_VALUE', 'en', 'Default');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_DESCRIPTION', 'en', 'Description');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('ENTANDO_API_SERVICE_DESCRIPTION', 'it', 'Descrizione');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Title', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Abstract', 'en', 'Abstract');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Body', 'en', 'Body');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Image1', 'en', 'Image1');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Image2', 'en', 'Image2');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Attach', 'en', 'Attach');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_CNG_Links', 'en', 'Links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_VideoCode', 'en', 'VideoCode');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_Title', 'en', 'Title');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_Abstract', 'en', 'Abstract');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_Body', 'en', 'Body');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_Attach', 'en', 'Attach');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_YTB_Links', 'en', 'Links');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_CNT', 'en', 'Contact us');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_Name', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_Surname', 'en', 'Surname');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_eMail', 'en', 'eMail');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_Message', 'en', 'Message');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_SAVE', 'en', 'Send Request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_CNT_SAVE', 'it', 'Invia Richiesta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SLOGAN_DESCRIPTION', 'en', 'Entando is a Java Open Source portal-like platform for making you happy building web, cloud, mobile and social enterprise-class solutions.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('SLOGAN_DESCRIPTION', 'it', 'Entando is a Java Open Source portal-like platform for making you happy building web, cloud, mobile and social enterprise-class solutions.');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_guest', 'en', '<strong>Welcome Guest!</strong>');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('WELCOME_guest', 'it', '<strong>Welcome Guest!</strong>');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_TITLE_VRF', 'en', 'Vacation Request Form');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_Name', 'en', 'Name');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_Surname', 'en', 'Surname');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_StartDate', 'en', 'Start Date');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_EndDate', 'en', 'End Date');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_SAVE', 'en', 'Send Request');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpwebdynamicform_VRF_SAVE', 'it', 'Invia Richiesta');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_NEWPAGE', 'en', 'New Page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_NEWPAGE', 'it', 'Nuova Pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDITPAGE', 'en', 'Edit Page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDITPAGE', 'it', 'Edita Pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_DELETEPAGE', 'en', 'Delete Page');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_DELETEPAGE', 'it', 'Cancella Pagina');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_POPUP_TITLE', 'en', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_POPUP_TITLE', 'it', 'Edit');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDIT_FRAME', 'en', 'Edit frame:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDIT_FRAME', 'it', 'Modifica Posizione:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EMPTY_FRAME', 'en', 'Empty frame:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EMPTY_FRAME', 'it', 'Svuola la posizione:');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDIT_THIS_CONTENT', 'en', 'Edit this content (Front Shortcut)');
INSERT INTO localstrings (keycode, langcode, stringvalue) VALUES ('jpfrontshortcut_EDIT_THIS_CONTENT', 'it', 'Modifica questo contenuto (Front Shortcut)');
