INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('13', 'Image', 'Logo Osor', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="13"><descr>Logo Osor</descr><groups mainGroup="free" /><categories /><masterfile>OSOR-logo.png</masterfile><instance><size>3</size><filename>OSOR-logo_d3.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>OSOR-logo_d2.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>OSOR-logo_d1.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>0</size><filename>OSOR-logo_d0.png</filename><mimetype>image/png</mimetype><weight>5 Kb</weight></instance></resource>
', 'OSOR-logo.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('14', 'Image', 'Banner Live Event Tzente - Pentaho - Bnova', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="14"><descr>Banner Live Event Tzente - Pentaho - Bnova</descr><groups mainGroup="free" /><categories /><masterfile>Banner_Evento.jpg</masterfile><instance><size>3</size><filename>Banner_Evento_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Banner_Evento_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Banner_Evento_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Banner_Evento_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>15 Kb</weight></instance></resource>
', 'Banner_Evento.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('16', 'Image', 'Banner Webcast integrazione Entando - Pentaho', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="16"><descr>Banner Webcast integrazione Entando - Pentaho</descr><groups mainGroup="free" /><categories /><masterfile>Webinar.png</masterfile><instance><size>3</size><filename>Webinar_d3.png</filename><mimetype>image/png</mimetype><weight>27 Kb</weight></instance><instance><size>2</size><filename>Webinar_d2.png</filename><mimetype>image/png</mimetype><weight>12 Kb</weight></instance><instance><size>1</size><filename>Webinar_d1.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>0</size><filename>Webinar_d0.png</filename><mimetype>image/png</mimetype><weight>56 Kb</weight></instance></resource>
', 'Webinar.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('18', 'Image', 'Entando IdeaScale', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="18"><descr>Entando IdeaScale</descr><groups mainGroup="free" /><categories /><masterfile>ideascale_logo.jpeg</masterfile><instance><size>3</size><filename>ideascale_logo_d3.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>2</size><filename>ideascale_logo_d2.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>1</size><filename>ideascale_logo_d1.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>ideascale_logo_d0.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance></resource>
', 'ideascale_logo.jpeg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('20', 'Image', 'Intranet Area', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="20"><descr>Intranet Area</descr><groups mainGroup="free" /><categories /><masterfile>Intranet_Area.jpg</masterfile><instance><size>3</size><filename>Intranet_Area_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Intranet_Area_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Intranet_Area_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Intranet_Area_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>239 Kb</weight></instance></resource>
', 'Intranet_Area.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('23', 'Image', 'Intranet Notice Board', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="23"><descr>Intranet Notice Board</descr><groups mainGroup="free" /><categories /><masterfile>Intranet_notice_board.jpg</masterfile><instance><size>3</size><filename>Intranet_notice_board_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Intranet_notice_board_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Intranet_notice_board_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Intranet_notice_board_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>801 Kb</weight></instance></resource>
', 'Intranet_notice_board.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('24', 'Image', 'Company Meeting', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="24"><descr>Company Meeting</descr><groups mainGroup="free" /><categories /><masterfile>Company_Meeting.jpg</masterfile><instance><size>3</size><filename>Company_Meeting_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>10 Kb</weight></instance><instance><size>2</size><filename>Company_Meeting_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Company_Meeting_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Company_Meeting_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>803 Kb</weight></instance></resource>
', 'Company_Meeting.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('10', 'Image', 'Meeting', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="10"><descr>Meeting</descr><groups mainGroup="free" /><categories /><masterfile>Live_Event_Tzente_Pentaho_Bnova_d5.jpg</masterfile><instance><size>3</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>2</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance></resource>
', 'Live_Event_Tzente_Pentaho_Bnova_d5.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('25', 'Image', 'Webcast Portal & BI', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="25"><descr>Webcast Portal &amp; BI</descr><groups mainGroup="free" /><categories /><masterfile>Webcast_Analytics.jpg</masterfile><instance><size>3</size><filename>Webcast_Analytics_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>9 Kb</weight></instance><instance><size>2</size><filename>Webcast_Analytics_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Webcast_Analytics_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Webcast_Analytics_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>576 Kb</weight></instance></resource>
', 'Webcast_Analytics.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('26', 'Image', 'Contribute', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="26"><descr>Contribute</descr><groups mainGroup="free" /><categories /><masterfile>Contribute.jpg</masterfile><instance><size>3</size><filename>Contribute_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>Contribute_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>1</size><filename>Contribute_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Contribute_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>124 Kb</weight></instance></resource>
', 'Contribute.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('29', 'Image', 'Live Event', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="29"><descr>Live Event</descr><groups mainGroup="free" /><categories /><masterfile>Live_Event.jpg</masterfile><instance><size>3</size><filename>Live_Event_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>10 Kb</weight></instance><instance><size>2</size><filename>Live_Event_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Live_Event_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Live_Event_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>497 Kb</weight></instance></resource>
', 'Live_Event.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('31', 'Image', 'Analytics', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="31"><descr>Analytics</descr><groups mainGroup="free" /><categories /><masterfile>Analytics.jpg</masterfile><instance><size>3</size><filename>Analytics_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>Analytics_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>Analytics_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Analytics_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>325 Kb</weight></instance></resource>
', 'Analytics.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('32', 'Image', 'Customer Services', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="32"><descr>Customer Services</descr><groups mainGroup="free" /><categories /><masterfile>Customer_services.jpg</masterfile><instance><size>3</size><filename>Customer_services_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>Customer_services_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>1</size><filename>Customer_services_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Customer_services_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>346 Kb</weight></instance></resource>
', 'Customer_services.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('37', 'Attach', 'Entando System Requirements', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="37"><descr>Entando System Requirements</descr><groups mainGroup="free" /><categories /><masterfile>Entando_System_Requirements.pdf</masterfile><instance><size>0</size><filename>Entando_System_Requirements.pdf</filename><mimetype>application/pdf</mimetype><weight>43 Kb</weight></instance></resource>
', 'Entando_System_Requirements.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('39', 'Attach', 'Product Card', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="39"><descr>Product Card</descr><groups mainGroup="free" /><categories /><masterfile>Product_Card.pdf</masterfile><instance><size>0</size><filename>Product_Card.pdf</filename><mimetype>application/pdf</mimetype><weight>65 Kb</weight></instance></resource>
', 'Product_Card.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('43', 'Attach', 'Business Plan', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="43"><descr>Business Plan</descr><groups mainGroup="free" /><categories /><masterfile>Business_Plan.pdf</masterfile><instance><size>0</size><filename>Business_Plan.pdf</filename><mimetype>application/pdf</mimetype><weight>40 Kb</weight></instance></resource>
', 'Business_Plan.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('46', 'Attach', 'Best Practice', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="46"><descr>Best Practice</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Plugin_Best_Practices.pdf</masterfile><instance><size>0</size><filename>Entando_Plugin_Best_Practices.pdf</filename><mimetype>application/pdf</mimetype><weight>39 Kb</weight></instance></resource>
', 'Entando_Plugin_Best_Practices.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('48', 'Attach', 'Intranet Documentation', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="48"><descr>Intranet Documentation</descr><groups mainGroup="free" /><categories /><masterfile>Intranet_Documentation.pdf</masterfile><instance><size>0</size><filename>Intranet_Documentation.pdf</filename><mimetype>application/pdf</mimetype><weight>27 Kb</weight></instance></resource>
', 'Intranet_Documentation.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('50', 'Attach', 'Customer Agreement', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="50"><descr>Customer Agreement</descr><groups mainGroup="free" /><categories /><masterfile>Customer_Agreement.pdf</masterfile><instance><size>0</size><filename>Customer_Agreement.pdf</filename><mimetype>application/pdf</mimetype><weight>40 Kb</weight></instance></resource>
', 'Customer_Agreement.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('52', 'Attach', 'Entando Model', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="52"><descr>Entando Model</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Model.pdf</masterfile><instance><size>0</size><filename>Entando_Model.pdf</filename><mimetype>application/pdf</mimetype><weight>78 Kb</weight></instance></resource>
', 'Entando_Model.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('57', 'Image', 'What is Entando', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="57"><descr>What is Entando</descr><groups mainGroup="free" /><categories /><masterfile>What_is_Entando.png</masterfile><instance><size>3</size><filename>What_is_Entando_d3.png</filename><mimetype>image/png</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>What_is_Entando_d2.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>What_is_Entando_d1.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>What_is_Entando_d0.png</filename><mimetype>image/png</mimetype><weight>43 Kb</weight></instance></resource>
', 'What_is_Entando.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('54', 'Image', 'My Entando APP', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="54"><descr>My Entando APP</descr><groups mainGroup="free" /><categories /><masterfile>APP.jpg</masterfile><instance><size>3</size><filename>APP_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>APP_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>APP_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>APP_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>45 Kb</weight></instance></resource>
', 'APP.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('28', 'Image', 'Entando Logo', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="28"><descr>Entando Logo</descr><groups mainGroup="free" /><categories /><masterfile>Entando_green_logo.png</masterfile><instance><size>3</size><filename>Entando_green_logo_d3.png</filename><mimetype>image/png</mimetype><weight>2 Kb</weight></instance><instance><size>2</size><filename>Entando_green_logo_d2.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>1</size><filename>Entando_green_logo_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Entando_green_logo_d0.png</filename><mimetype>image/png</mimetype><weight>5 Kb</weight></instance></resource>
', 'Entando_green_logo.png');
