INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('18', 'Image', 'Entando IdeaScale', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="18"><descr>Entando IdeaScale</descr><groups mainGroup="free" /><categories /><masterfile>ideascale_logo.jpeg</masterfile><instance><size>3</size><filename>ideascale_logo_d3.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>2</size><filename>ideascale_logo_d2.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>1</size><filename>ideascale_logo_d1.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>ideascale_logo_d0.jpeg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance></resource>
', 'ideascale_logo.jpeg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('20', 'Image', 'Intranet Area', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="20"><descr>Intranet Area</descr><groups mainGroup="free" /><categories /><masterfile>Intranet_Area.jpg</masterfile><instance><size>3</size><filename>Intranet_Area_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Intranet_Area_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Intranet_Area_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Intranet_Area_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>239 Kb</weight></instance></resource>
', 'Intranet_Area.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('23', 'Image', 'Intranet Notice Board', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="23"><descr>Intranet Notice Board</descr><groups mainGroup="free" /><categories /><masterfile>Intranet_notice_board.jpg</masterfile><instance><size>3</size><filename>Intranet_notice_board_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>6 Kb</weight></instance><instance><size>2</size><filename>Intranet_notice_board_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Intranet_notice_board_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Intranet_notice_board_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>801 Kb</weight></instance></resource>
', 'Intranet_notice_board.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('24', 'Image', 'Company Meeting', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="24"><descr>Company Meeting</descr><groups mainGroup="free" /><categories /><masterfile>Company_Meeting.jpg</masterfile><instance><size>3</size><filename>Company_Meeting_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>10 Kb</weight></instance><instance><size>2</size><filename>Company_Meeting_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Company_Meeting_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Company_Meeting_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>803 Kb</weight></instance></resource>
', 'Company_Meeting.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('10', 'Image', 'Meeting', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="10"><descr>Meeting</descr><groups mainGroup="free" /><categories /><masterfile>Live_Event_Tzente_Pentaho_Bnova_d5.jpg</masterfile><instance><size>3</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>2</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>3 Kb</weight></instance><instance><size>1</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Live_Event_Tzente_Pentaho_Bnova_d5_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance></resource>
', 'Live_Event_Tzente_Pentaho_Bnova_d5.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('25', 'Image', 'Webcast Portal & BI', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="25"><descr>Webcast Portal &amp; BI</descr><groups mainGroup="free" /><categories /><masterfile>Webcast_Analytics.jpg</masterfile><instance><size>3</size><filename>Webcast_Analytics_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>9 Kb</weight></instance><instance><size>2</size><filename>Webcast_Analytics_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Webcast_Analytics_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Webcast_Analytics_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>576 Kb</weight></instance></resource>
', 'Webcast_Analytics.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('26', 'Image', 'Contribute', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="26"><descr>Contribute</descr><groups mainGroup="free" /><categories /><masterfile>Contribute.jpg</masterfile><instance><size>3</size><filename>Contribute_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>Contribute_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>1</size><filename>Contribute_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Contribute_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>124 Kb</weight></instance></resource>
', 'Contribute.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('29', 'Image', 'Live Event', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="29"><descr>Live Event</descr><groups mainGroup="free" /><categories /><masterfile>Live_Event.jpg</masterfile><instance><size>3</size><filename>Live_Event_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>10 Kb</weight></instance><instance><size>2</size><filename>Live_Event_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>5 Kb</weight></instance><instance><size>1</size><filename>Live_Event_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Live_Event_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>497 Kb</weight></instance></resource>
', 'Live_Event.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('31', 'Image', 'Analytics', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="31"><descr>Analytics</descr><groups mainGroup="free" /><categories /><masterfile>Analytics.jpg</masterfile><instance><size>3</size><filename>Analytics_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>Analytics_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>Analytics_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>Analytics_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>325 Kb</weight></instance></resource>
', 'Analytics.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('32', 'Image', 'Customer Services', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="32"><descr>Customer Services</descr><groups mainGroup="free" /><categories /><masterfile>Customer_services.jpg</masterfile><instance><size>3</size><filename>Customer_services_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>2</size><filename>Customer_services_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>1</size><filename>Customer_services_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>Customer_services_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>346 Kb</weight></instance></resource>
', 'Customer_services.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('37', 'Attach', 'Setup Java Environment', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="37"><descr>Setup Java Environment</descr><groups mainGroup="free" /><categories /><masterfile>Setup a Java development environment for the Entando Platform.pdf</masterfile><instance><size>0</size><filename>Setup a Java development environment for the Entando Platform.pdf</filename><mimetype>application/pdf</mimetype><weight>353 Kb</weight></instance></resource>
', 'Setup a Java development environment for the Entando Platform.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('39', 'Attach', 'Product Details', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="39"><descr>Product Details</descr><groups mainGroup="free" /><categories /><masterfile>Entando Overview.pdf</masterfile><instance><size>0</size><filename>Entando Overview.pdf</filename><mimetype>application/pdf</mimetype><weight>592 Kb</weight></instance></resource>
', 'Entando Overview.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('43', 'Attach', 'Internal Company Procedures', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="43"><descr>Internal Company Procedures</descr><groups mainGroup="free" /><categories /><masterfile>Internal_Company_Procedures.pdf</masterfile><instance><size>0</size><filename>Internal_Company_Procedures.pdf</filename><mimetype>application/pdf</mimetype><weight>48 Kb</weight></instance></resource>
', 'Internal_Company_Procedures.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('46', 'Attach', 'Entando Customer Case Study Template', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="46"><descr>Entando Customer Case Study Template</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Customer_Case_study_EN_V1.0.pdf</masterfile><instance><size>0</size><filename>Entando_Customer_Case_study_EN_V1.0.pdf</filename><mimetype>application/pdf</mimetype><weight>74 Kb</weight></instance></resource>
', 'Entando_Customer_Case_study_EN_V1.0.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('48', 'Attach', 'Intranet Documentation', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="48"><descr>Intranet Documentation</descr><groups mainGroup="free" /><categories /><masterfile>Internal_Template_Documentation.pdf</masterfile><instance><size>0</size><filename>Internal_Template_Documentation.pdf</filename><mimetype>application/pdf</mimetype><weight>86 Kb</weight></instance></resource>
', 'Internal_Template_Documentation.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('50', 'Attach', 'Customer Agreement', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="50"><descr>Customer Agreement</descr><groups mainGroup="free" /><categories /><masterfile>Customer_Agreement.pdf</masterfile><instance><size>0</size><filename>Customer_Agreement.pdf</filename><mimetype>application/pdf</mimetype><weight>40 Kb</weight></instance></resource>
', 'Customer_Agreement.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('52', 'Attach', 'Entando Model', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="52"><descr>Entando Model</descr><groups mainGroup="free" /><categories /><masterfile>The Entando Model.pdf</masterfile><instance><size>0</size><filename>The Entando Model.pdf</filename><mimetype>application/pdf</mimetype><weight>444 Kb</weight></instance></resource>
', 'The Entando Model.pdf');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('57', 'Image', 'What is Entando', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="57"><descr>What is Entando</descr><groups mainGroup="free" /><categories /><masterfile>What_is_Entando.png</masterfile><instance><size>3</size><filename>What_is_Entando_d3.png</filename><mimetype>image/png</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>What_is_Entando_d2.png</filename><mimetype>image/png</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>What_is_Entando_d1.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>What_is_Entando_d0.png</filename><mimetype>image/png</mimetype><weight>43 Kb</weight></instance></resource>
', 'What_is_Entando.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('54', 'Image', 'My Entando APP', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="54"><descr>My Entando APP</descr><groups mainGroup="free" /><categories /><masterfile>APP.jpg</masterfile><instance><size>3</size><filename>APP_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>8 Kb</weight></instance><instance><size>2</size><filename>APP_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>4 Kb</weight></instance><instance><size>1</size><filename>APP_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>0</size><filename>APP_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>45 Kb</weight></instance></resource>
', 'APP.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('28', 'Image', 'Entando Logo', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="28"><descr>Entando Logo</descr><groups mainGroup="free" /><categories /><masterfile>Entando_green_logo.png</masterfile><instance><size>3</size><filename>Entando_green_logo_d3.png</filename><mimetype>image/png</mimetype><weight>2 Kb</weight></instance><instance><size>2</size><filename>Entando_green_logo_d2.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>1</size><filename>Entando_green_logo_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Entando_green_logo_d0.png</filename><mimetype>image/png</mimetype><weight>5 Kb</weight></instance></resource>
', 'Entando_green_logo.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('65', 'Image', 'Entando Logo', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="65"><descr>Entando Logo</descr><groups mainGroup="free" /><categories /><masterfile>entando_square_3_w.png</masterfile><instance><size>3</size><filename>entando_square_3_w_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>entando_square_3_w_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>entando_square_3_w_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>entando_square_3_w_d0.png</filename><mimetype>image/png</mimetype><weight>8 Kb</weight></instance></resource>
', 'entando_square_3_w.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('67', 'Image', 'Entando version 3.2', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="67"><descr>Entando version 3.2</descr><groups mainGroup="free" /><categories /><masterfile>iStock_000018618958XSmall.jpg</masterfile><instance><size>3</size><filename>iStock_000018618958XSmall_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>iStock_000018618958XSmall_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>iStock_000018618958XSmall_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>iStock_000018618958XSmall_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>89 Kb</weight></instance></resource>
', 'iStock_000018618958XSmall.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('68', 'Image', 'Training Entando 2013', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="68"><descr>Training Entando 2013</descr><groups mainGroup="free" /><categories /><masterfile>shutterstock_30166243.jpg</masterfile><instance><size>3</size><filename>shutterstock_30166243_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>shutterstock_30166243_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>shutterstock_30166243_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>shutterstock_30166243_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>630 Kb</weight></instance></resource>
', 'shutterstock_30166243.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('69', 'Image', 'Webinar', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="69"><descr>Webinar</descr><groups mainGroup="free" /><categories /><masterfile>future-400x300.jpg</masterfile><instance><size>3</size><filename>future-400x300_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>future-400x300_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>future-400x300_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>future-400x300_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>33 Kb</weight></instance></resource>
', 'future-400x300.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('72', 'Image', 'Events', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="72"><descr>Events</descr><groups mainGroup="free" /><categories /><masterfile>Participation.jpg</masterfile><instance><size>3</size><filename>Participation_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>Participation_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>Participation_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Participation_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>95 Kb</weight></instance></resource>
', 'Participation.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('74', 'Image', 'Communication', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="74"><descr>Communication</descr><groups mainGroup="free" /><categories /><masterfile>comunicazione.jpg</masterfile><instance><size>3</size><filename>comunicazione_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>comunicazione_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>comunicazione_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>comunicazione_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>20 Kb</weight></instance></resource>
', 'comunicazione.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('75', 'Image', 'Satisfaction', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="75"><descr>Satisfaction</descr><groups mainGroup="free" /><categories /><masterfile>employee_satisfaction.jpg</masterfile><instance><size>3</size><filename>employee_satisfaction_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>employee_satisfaction_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>employee_satisfaction_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>employee_satisfaction_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>8 Kb</weight></instance></resource>
', 'employee_satisfaction.jpg');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('76', 'Image', 'Editing', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="76"><descr>Editing</descr><groups mainGroup="free" /><categories /><masterfile>Entando_Demo_Editing.png</masterfile><instance><size>3</size><filename>Entando_Demo_Editing_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>Entando_Demo_Editing_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>Entando_Demo_Editing_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>Entando_Demo_Editing_d0.png</filename><mimetype>image/png</mimetype><weight>2 Kb</weight></instance></resource>
', 'Entando_Demo_Editing.png');
